version: '3.8'

services:
  rabbitholes-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3009:3000"
    environment:
      - PORT=3009
      - NODE_ENV=production
      # Add your API keys here or use a .env file
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3009/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
